name: 编译32位ARM
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 安装Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: 编译32位ARMv7（已修复报错）
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 \
          go build -v \
          -tags goolm,stdjson \
          -ldflags "-s -w" \
          -o dist/picoclaw ./cmd/picoclaw

      - name: 上传可下载文件
        uses: actions/upload-artifact@v4
        with:
          name: 32位可执行文件
          path: dist/picoclaw
